### ISSUE TITLE
Encourage people to deploy their own instances

### ISSUE THREAD

**Issue by kytta** [kytta/share2fedi#38]
V3 will support more deployment variants, including Netlify, Cloudflare, and maybe even Deno Deploy. There also needs to be a section in the docs encouraging people to make their own instances for their sites. The serverless providers make this very easy, and it costs nothing (at least for me (at least for now)). We need to make it clear, that the default instance is getting way too popular.

Also for this issue: We need to ask dev.to to do this, maybe even before the docs update

**Comment by sunny** [comment]
Some thoughts here, related to v3 & translations: the fact that it mentions `s2f.kytta.dev`, `Vercel` and links to `s2f.kytta.dev`’s Status page means that anybody wanting to make theire own instance need to also update the texts, which is not ideal.

I don’t know how best to handle this (detect the domain & the host, make an easy to update configuration file, …), but thought I should mention it.
